apiVersion: v1
kind: Service
metadata:
  name: timesheet
  namespace: ts
spec:
  selector:
    app: timesheet
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timesheet
  namespace: ts
spec:
  selector:
    matchLabels:
      app: timesheet
  template:
    metadata:
      labels:
        app: timesheet
    spec:
      containers:
      - name: timesheet
        image: ts:01
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: timesheet-config
